const express = require("express")
require("dotenv").config()
const App = require("./config/app")
const MobileRouterV2 = require("./router/mobileApiV2.router")
const baseMiddleware = require("./config/baseMiddleware")
const { webApiV2 } = require("./router/webApiV2.router")
const Response = require("./config/response")
const app = express()
app.use(baseMiddleware);
app.get("/", Response.index)
app.use("/dashboard-api/v2", webApiV2)
app.use("/mobile-api/v2", MobileRouterV2)
app.use("/", Response.notFound)
app.listen(App.PORT, "0.0.0.0", () => {
    console.log(`Server running in http://localhost:${App.PORT}`)
})
